version: '3.5'
services:
  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    networks:
      - wex
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 30
      
  transactionmanager:
    build: .
    container_name: transactionmanager
    hostname: transactionmanager
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - wex
    environment:
      SERVER_PORT: 8080
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    restart: always
networks:
  wex:
    driver: bridge
